//
//  CollectionSectionModel.swift
//  ModelGen
//
//  Generated by [ModelGen](https://github.com/hebertialmeida/ModelGen)
//  Copyright © 2018 ModelGen. All rights reserved.
//

import Foundation

public struct CollectionSectionModel: Codable {

    // MARK: Instance Variables

    public let id: String
    public let date: Date
    public let collections: [Collection]

    private enum CodingKeys: String, CodingKey {
        case id
        case date
        case collections
    }
}

// MARK: - Diffable

extension CollectionSectionModel: Diffable, DiffableBoxProtocol {
    public var diffIdentifier: String {
        return "\(id)"
    }

    static public func == (lhs: CollectionSectionModel, rhs: CollectionSectionModel) -> Bool {
        guard lhs.id == rhs.id else { return false }
        guard lhs.date == rhs.date else { return false }
        guard lhs.collections == rhs.collections else { return false }
        return true
    }
}