//
//  PhotoLinks.swift
//  ModelGen
//
//  Generated by [ModelGen](https://github.com/hebertialmeida/ModelGen)
//  Copyright © 2020 ModelGen. All rights reserved.
//

import Foundation

public struct PhotoLinks: Codable, Equatable {
    public let download: URL
    public let downloadLocation: URL
    public let html: URL

    private enum CodingKeys: String, CodingKey {
        case download
        case downloadLocation = "download_location" 
        case html
    }
}

// MARK: - Equatable

public func == (lhs: PhotoLinks, rhs: PhotoLinks) -> Bool {
    guard lhs.download == rhs.download else { return false }
    guard lhs.downloadLocation == rhs.downloadLocation else { return false }
    guard lhs.html == rhs.html else { return false }
    return true
}