//
//  PhotoUrl.swift
//  ModelGen
//
//  Generated by [ModelGen](https://github.com/hebertialmeida/ModelGen)
//  Copyright © 2018 ModelGen. All rights reserved.
//

import Foundation

public struct PhotoUrl: Codable {

    // MARK: Instance Variables

    public let full: URL
    public let small: URL
    public let thumb: URL
    public let regular: URL
    public let raw: URL

    private enum CodingKeys: String, CodingKey {
        case full
        case small
        case thumb
        case regular
        case raw
    }
}

// MARK: - Equatable

public func == (lhs: PhotoUrl, rhs: PhotoUrl) -> Bool {
    guard lhs.full == rhs.full else { return false }
    guard lhs.small == rhs.small else { return false }
    guard lhs.thumb == rhs.thumb else { return false }
    guard lhs.regular == rhs.regular else { return false }
    guard lhs.raw == rhs.raw else { return false }
    return true
}