//
//  PhotoSectionModel.swift
//  ModelGen
//
//  Generated by [ModelGen](https://github.com/hebertialmeida/ModelGen)
//  Copyright © 2020 ModelGen. All rights reserved.
//

import Foundation

public struct PhotoSectionModel: Codable, Equatable {
    public let date: Date
    public let id: String
    public let photos: [Photo]

    private enum CodingKeys: String, CodingKey {
        case date
        case id
        case photos
    }
}

// MARK: - Equatable

public func == (lhs: PhotoSectionModel, rhs: PhotoSectionModel) -> Bool {
    guard lhs.date == rhs.date else { return false }
    guard lhs.id == rhs.id else { return false }
    guard lhs.photos == rhs.photos else { return false }
    return true
}