//
//  PreviewPhoto.swift
//  ModelGen
//
//  Generated by [ModelGen](https://github.com/hebertialmeida/ModelGen)
//  Copyright © 2018 ModelGen. All rights reserved.
//

import Foundation

public struct PreviewPhoto: Codable {

    // MARK: Instance Variables

    public let id: String
    public let urls: PhotoUrls

    private enum CodingKeys: String, CodingKey {
        case id
        case urls
    }
}

// MARK: - Diffable

extension PreviewPhoto: Diffable, DiffableBoxProtocol {
    public var diffIdentifier: String {
        return "\(id)"
    }

    static public func == (lhs: PreviewPhoto, rhs: PreviewPhoto) -> Bool {
        guard lhs.id == rhs.id else { return false }
        guard lhs.urls == rhs.urls else { return false }
        return true
    }
}
