//
//  PreviewPhoto.swift
//  ModelGen
//
//  Generated by [ModelGen](https://github.com/hebertialmeida/ModelGen)
//  Copyright © 2018 ModelGen. All rights reserved.
//

import Foundation

public struct PreviewPhoto: Codable, Equatable {

    // MARK: Instance Variables

    public let id: Int
    public let urls: PhotoUrls

    private enum CodingKeys: String, CodingKey {
        case id
        case urls
    }
}

// MARK: - Equatable

public func == (lhs: PreviewPhoto, rhs: PreviewPhoto) -> Bool {
    guard lhs.id == rhs.id else { return false }
    guard lhs.urls == rhs.urls else { return false }
    return true
}