//
//  ProfileImage.swift
//  ModelGen
//
//  Generated by [ModelGen](https://github.com/hebertialmeida/ModelGen)
//  Copyright © 2018 ModelGen. All rights reserved.
//

import Foundation

public struct ProfileImage: Codable, Equatable {

    // MARK: Instance Variables

    public let medium: URL?
    public let small: URL?
    public let large: URL?

    private enum CodingKeys: String, CodingKey {
        case medium
        case small
        case large
    }
}

// MARK: - Equatable

public func == (lhs: ProfileImage, rhs: ProfileImage) -> Bool {
    guard lhs.medium == rhs.medium else { return false }
    guard lhs.small == rhs.small else { return false }
    guard lhs.large == rhs.large else { return false }
    return true
}