//
//  ProfileImage.swift
//  ModelGen
//
//  Generated by [ModelGen](https://github.com/hebertialmeida/ModelGen)
//  Copyright © 2020 ModelGen. All rights reserved.
//

import Foundation
import RocketData

public struct ProfileImage: Codable, Equatable {
    public let large: URL?
    public let medium: URL?
    public let small: URL?

    private enum CodingKeys: String, CodingKey {
        case large
        case medium
        case small
    }
}

// MARK: - Equatable

public func == (lhs: ProfileImage, rhs: ProfileImage) -> Bool {
    guard lhs.large == rhs.large else { return false }
    guard lhs.medium == rhs.medium else { return false }
    guard lhs.small == rhs.small else { return false }
    return true
}

// MARK: - Identifiable

extension ProfileImage: Hashable, Identifiable {
    public var id: Int {
        self.hashValue
    }
}

// MARK: - RocketData

extension ProfileImage: Model {
    public func map(_ transform: (Model) -> Model?) -> ProfileImage? {
        return self
    }

    public func forEach(_ visit: (Model) -> Void) {
    }
}