//
//  User.swift
//  ModelGen
//
//  Generated by [ModelGen](https://github.com/hebertialmeida/ModelGen)
//  Copyright © 2018 ModelGen. All rights reserved.
//

import Foundation

/// Definition of a User
public struct User: Codable {

    // MARK: Instance Variables

    public let profileImage: ProfileImage
    public let name: String
    public let location: String?
    public let id: String
    public let username: String
    public let bio: String?

    private enum CodingKeys: String, CodingKey {
        case profileImage = "profile_image" 
        case name
        case location
        case id
        case username
        case bio
    }
}

// MARK: - Equatable

public func == (lhs: User, rhs: User) -> Bool {
    guard lhs.profileImage == rhs.profileImage else { return false }
    guard lhs.name == rhs.name else { return false }
    guard lhs.location == rhs.location else { return false }
    guard lhs.id == rhs.id else { return false }
    guard lhs.username == rhs.username else { return false }
    guard lhs.bio == rhs.bio else { return false }
    return true
}